"""
Postmortem generator — writes INC-YYYY-XXX.md after incident resolution.
"""
import os
from datetime import datetime, timezone
from typing import Optional
from incident.model import IncidentRecord
from config import settings


POSTMORTEM_TEMPLATE = """\
# {incident_id}

> **Status**: {status} | **Severity**: {severity} | **Confidence**: {confidence}

---

## Incident Summary

**Service**: `{affected_service}`
**Alert**: {alert_name}
**Description**: {alert_description}

**Detected at**: {detected_at}
**Resolved at**: {resolved_at}
**Total Resolution Time**: {resolution_time}

---

## Impact

- Cache node `{affected_service}` was degraded or unavailable.
- Traffic was automatically re-routed to remaining healthy nodes via the Consistent Hash Ring.
- The AI SRE Agent detected and remediated this incident autonomously with human approval.

---

## Detection

{detection_details}

---

## Symptoms

{symptoms}

---

## Evidence Collected (OODA: Observe + Orient)

{evidence_summary}

---

## OODA Loop Steps

{ooda_steps}

---

## Root Cause Analysis

{root_cause}

---

## Remediation Actions (OODA: Decide + Act)

{actions}

### Human Approval
- **Approval ID**: `{approval_id}`
- **Approval Status**: {approval_status}

---

## Verification (OODA: Verify)

{verification}

---

## Tools Called

{tools_called}

---

## Preventive Recommendations

1. Configure bounded eviction policy (LRU recommended) to prevent unbounded cache growth.
2. Set JVM heap alerts at 75% (warning) and 90% (critical) to detect pressure early.
3. Consider increasing `-Xmx` if heap pressure is frequent under normal load.
4. Review `cache.max-size` in `application.yml` to match available JVM heap.
5. Enable Prometheus alerting for cache eviction spike rate as an early indicator.

---

*Generated by AI SRE Agent — {generated_at}*
"""


async def generate_postmortem(incident: IncidentRecord) -> str:
    """
    Generate a Markdown postmortem and save it to the incidents/ directory.
    Returns the file path.
    """
    incidents_dir = getattr(settings, "incidents_dir", "./incidents")
    os.makedirs(incidents_dir, exist_ok=True)

    # Format symptoms
    symptoms_md = "\n".join(f"- {s}" for s in incident.symptoms) or "- No symptoms recorded"

    # Format evidence
    evidence_lines = []
    for e in incident.evidence:
        evidence_lines.append(f"### {e.tool_name} ({e.source})")
        evidence_lines.append(f"*Collected at: {e.collected_at}*\n")
        if isinstance(e.data, dict):
            for k, v in list(e.data.items())[:8]:
                evidence_lines.append(f"- **{k}**: {v}")
        evidence_lines.append("")

    # Format OODA steps
    ooda_lines = []
    for step in incident.ooda_steps:
        ooda_lines.append(f"**[{step.phase}]** {step.summary} *(at {step.timestamp})*")

    # Format actions
    actions_md = "\n".join(f"{i+1}. {a}" for i, a in enumerate(incident.actions_executed)) or "- No actions executed"

    # Format tools
    tools_md = ", ".join(f"`{t}`" for t in dict.fromkeys(incident.tools_called)) or "None"

    # Resolution time
    if incident.resolution_time_seconds:
        mins = int(incident.resolution_time_seconds // 60)
        secs = int(incident.resolution_time_seconds % 60)
        resolution_time = f"{mins}m {secs}s"
    else:
        resolution_time = "N/A"

    content = POSTMORTEM_TEMPLATE.format(
        incident_id=incident.incident_id,
        status=incident.status.value,
        severity=incident.severity.value,
        confidence=incident.confidence or "UNKNOWN",
        affected_service=incident.affected_service,
        alert_name=incident.alert_name or "Manual trigger",
        alert_description=incident.alert_description or "N/A",
        detected_at=incident.detected_at,
        resolved_at=incident.resolved_at or "N/A",
        resolution_time=resolution_time,
        detection_details=f"Prometheus alert `{incident.alert_name}` triggered detection pipeline.",
        symptoms=symptoms_md,
        evidence_summary="\n".join(evidence_lines) or "No evidence collected.",
        ooda_steps="\n".join(ooda_lines) or "No OODA steps recorded.",
        root_cause=incident.root_cause or "Root cause undetermined.",
        actions=actions_md,
        approval_id=incident.approval_id or "N/A",
        approval_status=incident.approval_status or "N/A",
        verification=incident.verification_result or "Verification not completed.",
        tools_called=tools_md,
        generated_at=datetime.now(timezone.utc).isoformat(),
    )

    filename = f"{incident.incident_id}.md"
    filepath = os.path.join(incidents_dir, filename)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)

    return filepath
