apiVersion: v1
kind: Service
metadata:
  name: cache-node-headless
  namespace: cache-platform
  labels:
    app: cache-node
spec:
  clusterIP: None
  ports:
    - port: 8081
      name: http
  selector:
    app: cache-node
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cache-node
  namespace: cache-platform
  labels:
    app: cache-node
spec:
  serviceName: cache-node-headless
  replicas: 3
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: cache-node
  template:
    metadata:
      labels:
        app: cache-node
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8081"
    spec:
      containers:
        - name: cache-service
          image: ghcr.io/gulamhasan01/cache-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: http
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SERVER_PORT
              value: "8081"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: JAVA_OPTS
              value: "-Xms512m -Xmx512m -XX:+UseG1GC"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /api/v1/cluster/health/ping
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
          volumeMounts:
            - name: cache-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: cache-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
