apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: cache-platform
  labels:
    app: gateway-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: gateway-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: cache-platform
  labels:
    app: gateway-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: gateway-service
          image: ghcr.io/gulamhasan01/gateway-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: CLUSTER_NODES
              value: "cache-node-0.cache-node-headless:8081,cache-node-1.cache-node-headless:8081,cache-node-2.cache-node-headless:8081"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
